org: tas09009
app: aws_wrec_lambda
service: aws_wrec_lambda

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements
provider:
  name: aws
  profile: serverless-admin
  region: us-east-1

custom:
  dotenv:
    path: ../.env

  # Database URLs for different states
  dev:
    DATABASE_URL: postgresql+psycopg2://wnsqfvbk:GHl5Sq3gPJQHDgjwbMou4ZO6f7AE-oe0@mahmud.db.elephantsql.com/wnsqfvbk
  prod:
    DATABASE_URL: postgresql://tzmyhyab:VcSEcoqgi7hWdtUnUKqta9B2oVYSVc6f@mahmud.db.elephantsql.com/tzmyhyab
  test:
    DATABASE_URL: postgresql+psycopg2://seupapiy:4Ki4A2gKXs70TMb8xq_fXrJq8aJGmfGz@batyr.db.elephantsql.com/seupapiy

functions:
  processCsv:
    handler: handler.function
    environment:
      DATABASE_URL: ${self:custom.${opt:stage, 'dev'}.DATABASE_URL}
    events:
      - s3:
          bucket: wrec-upload-book-csv
          event: s3:ObjectCreated:*
          existing: true
