"""empty message

Revision ID: 39bf7d5fdc9a
Revises: 4f834e50fcfb
Create Date: 2021-09-06 16:09:19.825061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39bf7d5fdc9a'
down_revision = '4f834e50fcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'year_publish_original')
    op.drop_column('books', 'my_rating')
    op.drop_column('books', 'pages')
    op.drop_column('books', 'book_id')
    op.drop_column('books', 'additional_authors')
    op.drop_column('books', 'date_read')
    op.drop_column('books', 'avg_rating')
    op.drop_column('books', 'year_publish')
    op.drop_column('books', 'binding')
    op.drop_column('books', 'date_added')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'bookshelves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('bookshelves', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('date_added', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('binding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('year_publish', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('avg_rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('date_read', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('additional_authors', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('book_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('my_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('year_publish_original', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
