"""dewey levels

Revision ID: 80b0ea80d3c8
Revises:
Create Date: 2023-04-11 14:14:34.416049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b0ea80d3c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dewey_decimal_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dewey_level_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('dewey_decimal_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dewey_decimal_system_id'], ['dewey_decimal_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dewey_level_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('dewey_decimal_system_id', sa.Integer(), nullable=True),
    sa.Column('level_1_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dewey_decimal_system_id'], ['dewey_decimal_system.id'], ),
    sa.ForeignKeyConstraint(['level_1_id'], ['dewey_level_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dewey_level_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('dewey_decimal_system_id', sa.Integer(), nullable=True),
    sa.Column('level_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dewey_decimal_system_id'], ['dewey_decimal_system.id'], ),
    sa.ForeignKeyConstraint(['level_2_id'], ['dewey_level_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dewey_level_3')
    op.drop_table('dewey_level_2')
    op.drop_table('dewey_level_1')
    op.drop_table('dewey_decimal_system')

    # start id's at 1, rather than where they left off in the upgrade/downgrade
    # reset the sequence for the id column in dewey_level_1 table
    op.execute("SELECT setval('dewey_level_1_id_seq', 1, false);")
    op.execute("SELECT setval('dewey_level_2_id_seq', 1, false);")
    op.execute("SELECT setval('dewey_level_3_id_seq', 1, false);")
    op.execute("SELECT setval('dewey_decimal_system_id_seq', 1, false);")
    # ### end Alembic commands ###
