"""users_books

Revision ID: bf3b1e743b3c
Revises: fef9b0786ec2
Create Date: 2023-04-14 12:53:31.745912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3b1e743b3c'
down_revision = 'fef9b0786ec2'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('books', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['books'], ['books.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_books')
    # ### end Alembic commands ###
