org: tas09009
app: process-books
service: wrec-lambda

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
  dotenv:
    path: ../.env
    # requirements.txt caching issue when removing boto3
    # useDownloadCache: false

provider:
  name: aws
  runtime: python3.9

functions:
  processCsv:
    handler: handler.handler
    role: arn:aws:iam::831261256492:role/wrec-lambda-dev-IamRoleCustomResourcesLambdaExecuti-t9OkPM5Nqia3 # S3 permissions
    environment:
      DATABASE_URL: "postgresql+psycopg2://seupapiy:4Ki4A2gKXs70TMb8xq_fXrJq8aJGmfGz@batyr.db.elephantsql.com/seupapiy"
      # DATABASE_URL: ${env:DATABASE_URL} # References 'test' db

    events:
      - s3:
          bucket: wrec-upload-book-csv
          event: s3:ObjectCreated:*
          existing: true

